services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
      POSTGRES_DB: shopdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

  # ────────────────────────────────────────────────────────────────
  #  API  (FastAPI + Alembic + все зависимости из backend/Dockerfile)
  # ────────────────────────────────────────────────────────────────
  api:
    build:    
      context: ./backend         # папка, где лежит ваш Dockerfile
      dockerfile: Dockerfile     # (имя по-умолчанию; можно опустить)
    working_dir: /app            # задано в Dockerfile, но не мешает
    volumes:
      - ./backend/app/static:/app/static        # оставить, если нужна «живая» статика
      - ./backend/app:/app                      # горячий reload кода
    env_file:
      - webapp/.env.production                 # JWT_SECRET и др.
    depends_on: [db]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    environment:
      PYTHONPATH: /app
      ALEMBIC_CONFIG: /app/alembic.ini
    ports: ["8001:8001"]

  # ────────────────────────────────────────────────────────────────
  #  BOT (оставляем как есть: отдельный Dockerfile в backend/bot )
  # ────────────────────────────────────────────────────────────────
  bot:
    build:
      context: ./backend/bot
      dockerfile: Dockerfile
    working_dir: /bot
    command: python main.py
    volumes:
      - ./backend/bot:/bot
    env_file:
      - webapp/.env.production  
    depends_on: [api]

  # ────────────────────────────────────────────────────────────────
  #  NODE (фронт dev-server) — без изменений
  # ────────────────────────────────────────────────────────────────
  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./webapp:/app
    ports: ["5173:5173"]
    command: ["npm", "run", "dev"]

volumes:
  pgdata:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450