
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
      POSTGRES_DB: shopdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

  api:
    image: python:3.12-slim
    working_dir: /code
    command: >
      sh -c "pip install fastapi[all] sqlmodel psycopg2-binary requests init-data-py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
    volumes:
      - ./backend/app/static:/code/app/static
      - ./backend/app:/code/app
    depends_on: [db]
    env_file: .env.production
    ports: ["8001:8001"]

  bot:
    build: ./backend/bot          # ← одна строка, без context
    working_dir: /bot
    command: python main.py
    volumes:
      - ./backend/bot:/bot
    env_file: .env
    depends_on: [api]

  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./webapp:/app
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
volumes:
  pgdata:
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450